version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env/development
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgis/postgis
    env_file:
      - ./.env/development
    ports:
      - 5430:5432
