# Generated by Django 3.2.4 on 2021-06-19 07:33

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_spacetime.timeseries_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SpatialPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_spacetime.spatialpolygon_set+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SpatialPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_spacetime.spatialpoint_set+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceTimePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_spacetime.spacetimepoint_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='timeseries',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialpolygon',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geometry'], name='geometry_space_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialpoint',
            index=django.contrib.postgres.indexes.GistIndex(fields=['point'], name='point_space_idx'),
        ),
        migrations.AddIndex(
            model_name='spacetimepoint',
            index=django.contrib.postgres.indexes.GistIndex(fields=['point'], name='spacetime_point_idx'),
        ),
        migrations.AddIndex(
            model_name='spacetimepoint',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='spacetimestamp_idx'),
        ),
    ]
