# Generated by Django 3.2.4 on 2021-06-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.IntegerField()),
                ('iteration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('pac', models.IntegerField(primary_key=True, serialize=False)),
                ('artists', models.ManyToManyField(to='people.Artist')),
                ('categories', models.ManyToManyField(to='works.Category')),
                ('organizations', models.ManyToManyField(to='people.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.iteration')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='works.status')),
            ],
        ),
        migrations.AddField(
            model_name='iteration',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work'),
        ),
    ]
