# Generated by Django 3.2.4 on 2021-06-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citydata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='citydata',
            name='slug',
        ),
    ]
